import { DEFAULT_GROUPS, DEFAULT_MIC_GAIN, clampMicGain } from "./names.ts";

/**
 * Building the Comms link.
 *
 * Comms (https://vdo.ninja/comms.html, also served as https://comms.cam) is
 * VDO.Ninja's intercom app: audio-only by default, phone-first, with a row of
 * group buttons for choosing who you talk to. That is the entire Noisy Room
 * experience; this site only has to mint the room, hand out the link, and keep
 * the list of groups that everyone's buttons are built from.
 *
 * By default we open our own copy of it, /comms.html, generated by
 * scripts/update-comms.mjs with the "group: " button prefix removed. The
 * audio engine it embeds still comes from vdo.ninja.
 */

export const DEFAULT_COMMS_URL = "/comms.html";

export type CommsLink = {
  room: string;
  /** Side room ids. The built-in groups always come first. */
  sideRooms?: string[];
  /** Display name shown beside the person's audio in Comms. */
  label?: string;
  /** Starting microphone gain in percent. Defaults to DEFAULT_MIC_GAIN, not VDO.Ninja's 100. */
  micGain?: number;
  /**
   * Where Comms lives: a path on this site (the default) or an absolute URL
   * such as https://comms.cam/ to use the upstream app unpatched.
   */
  base?: string;
};

export function commsUrl({ room, sideRooms = [], label, micGain, base }: CommsLink): string {
  const target = base ?? process.env.NEXT_PUBLIC_COMMS_URL ?? DEFAULT_COMMS_URL;
  const params = new URLSearchParams();
  params.set("room", room);
  // `groups` (plural) only defines the buttons. The singular `group` would also
  // be passed through to the inner VDO.Ninja frame and silently join it.
  params.set("groups", [...DEFAULT_GROUPS, ...sideRooms].join(","));
  const name = label?.trim();
  if (name) params.set("label", name);
  // Comms forwards the whole query string to the VDO.Ninja frame inside it, so
  // guest-side audio options can ride along. `mediasettings` gives each person
  // their own gear menu (gain slider, auto-gain, noise suppression); without it
  // only a director may touch those.
  params.set("mediasettings", "");
  // Always sent: our starting level is deliberately not VDO.Ninja's.
  params.set("audiogain", String(clampMicGain(micGain ?? DEFAULT_MIC_GAIN)));
  // URLSearchParams writes a valueless flag as "mediasettings="; VDO.Ninja
  // accepts both, but the bare form is what its documentation shows.
  const query = params.toString().replace(/=(?=&|$)/g, "");

  // A same-site path stays relative, so it works as an href without the
  // server needing to know its own origin.
  if (target.startsWith("/")) return `${target}?${query}`;
  const url = new URL(target);
  url.search = query;
  return url.toString();
}

/** The page on this site that a QR code points at. */
export function roomPath(room: string): string {
  return `/r/${encodeURIComponent(room)}`;
}
